### PR TITLE
Advanced log

### PR DESCRIPTION
**Pull request by PhilipeLouchtch**
**Note: please do not squash, too many commits**

This PR introduces an advanced state log, that records the following mutations to a state:
- Initialize (record the initial state, this is parent-less or parent-disregarding operation)
- Apply 'Op' (records the mutation operation of type `AtomicObjectState[A]#Op` and the state, i.e. parent, on which it was applied)
- Merge (the parents and the conflict resolution mechanism used)

The log is heavily inspired by Event Sourcing combined with a git-like change recording model.

Furthermore, this PR includes the `conflict-resolution-mechanism` branch

### CODE REVIEW

**Comment by steffansluis** [comment]
@PhilipeLouchtch  image

Don't forget about this! Also, if you want to do a 'partial-squash', try an interactive rebase!

**Comment by PhilipeLouchtch** [comment]
Great, now I need to solve merges on per-commit basis.
So far, not very happy with this rebase-only strategy, to put it mildly.

Please just let me merge it normally. I do not wish to change the history, I do not wish to solve per-commit conflicts.

**Comment by steffansluis** [comment]
I've re-enabled merges, the point is not to annoy you or prevent you from working in the way you want. I personally prefer my merge conflicts to be on a per-commit basis as then the solution and the commit are grouped together as I rebase my work and I can solve each conflict in the context that it occurs in, rather than in some mashed up version all grouped together. We simply do not agree on the importance of preserving history, and I think this is the main reason rebasing does not work for you. I urge you to reconsider rebasing under the assumption that history doesn't matter (as I think you end up with a much cleaner history in the end, and you can still track everything in terms of PRs on Github if you like) and see if it is still so much trouble for you to work with.

**Comment by PhilipeLouchtch** [comment]
Thanks! We’re simply not working in a flow that works with this rebase only model. Furthermore, we have lots of branches that dpawn other branches. With rebasing, it makes improssible to use the branches overview to see whats stale and what’s not!

So all in all, in this project it does not contribute and in some cases cost extra time (like this discussion, and attempts getting things to work). And if a tool does not help, then it’s not a tool but an obstacle.

**Comment by steffansluis** [comment]
Oof...I wholeheartedly disagree with all of that, but I think this is simply a matter of preferred style. I will continue to use rebases and have a clean history and per-commit merge conflicts :upside_down_face:

**Pull request merged**
